### ISSUE TITLE
missing ui assets

### ISSUE THREAD

**Issue by scottleedavis** [Netflix/sleepy-puppy#1]
When using https://github.com/Netflix/sleepy-puppy-docker , sleepy-puppy is missing assets in the UI that make it near unusable.

fails w/404's on:
- static/admin/vendor/jquery-2.1.1.min.js 
- static/admin/bootstrap/bootstrap3/css/bootstrap.min.css 
- static/admin/bootstrap/bootstrap3/css/bootstrap-theme.min.css 
- static/admin/admin/css/bootstrap3/admin.css 
- static/admin/bootstrap/bootstrap3/js/bootstrap.min.js 
- static/admin/vendor/moment-2.8.4.min.js 
- static/admin/vendor/select2/select2.min.js

adding these files (and there are many more on other pages..... mostly in the 'static/admin' location, looks like it fixes the missing static assets.

**Comment by scriptsrc** [comment]
Are you using boot2docker?  I was having similar issues and I am not using boot2docker.  Everything was working great for @sbehrens and he was using boot2docker.  I don't understand how one way or another would affect the loading of static files, but I'm just curious.

**Comment by scottleedavis** [comment]
I am not using boot2docker, rather the latest Docker Toolbox / "docker quickstart terminal"....      the requirements are for both boot2docker and docker toolbox?

been reading that the latest toolbox replaces boot2docker...

**Comment by sbehrens** [comment]
I noticed the same thing, I have been using boot2docker but just noticed that is being phased out by docker machine.  @monkeysecurity and I will need to test with docker-machine and see if we can reproduce the issue.

**Comment by sbehrens** [comment]
I noticed the same thing, I have been using boot2docker but just noticed that is being phased out by docker machine. @monkeysecurity and I will need to test with docker-machine and see if we can reproduce the issue.

**Comment by sbehrens** [comment]
reproduced issue using docker-machine:

![](http://i.snag.gy/0fk7q.jpg)

**Comment by mtparet** [comment]
reproduced under Ubuntu (boot2docker needs to be used only on Mac OS and Windows)

**Comment by scriptsrc** [comment]
I haven't committed any changes yet, but it appears to be fixed if you remove the following from `nginx/sites-available/sleepy_puppy`

```
location /static {
    alias /usr/local/src/sleepy-puppy/sleepypuppy/static;
    autoindex on;
}
```

I'll test this a bit more and update the repo when I'm ready.

**Comment by sbehrens** [comment]
Resolved in latest commit.
