### ISSUE TITLE
sleepy-puppy does not send email notification

### ISSUE THREAD

**Issue by pwneddesal** [Netflix/sleepy-puppy#10]
I have followed the quick[ tutorial here ](https://github.com/netflix/sleepy-puppy/wiki/setup)after i successfully setup the sleepy-puppy. however sleepy-puppy does not send me a notification if the xss payload is triggered. I look into the logs and it seems there is a error in `File "/apps/sleepy-puppy/sleepypuppy/collector/views.py", line 201,`

[sleepylog.txt](https://github.com/Netflix/sleepy-puppy/files/437495/sleepy.txt)

**Comment by pwneddesal** [comment]
just for update. look like the error is for Amazon Web Services;  i am using digitalocean.

**Comment by sbehrens** [comment]
Sleepy Puppy leverages AWS for email notifications, however this can be disabled if you would rather use your own SMTP server.  

In the root of sleepy-puppy, simply change the following configuration setting:

``` python
# Email server configuration
# SES Options:
EMAILS_USE_SES = True
SES_REGION = 'us-east-1'
```

Set `EMAILS_USE_SES` to False and configure the SMTP settings below in the same configuration file.  

Please reopen this issue if you have any other questions.
