### ISSUE TITLE
Denial of Service

### ISSUE THREAD

**Issue by ewilded** [Netflix/sleepy-puppy#13]
The /up page taking uploaded screenshots is somehow susceptible to a denial of service condition.
After sending precisely 27 screenshot-uploading requests the server application crashes.
Repeated multiple times with different filenames and contents - there was no difference, it kept crashing exactly after the 27-th request. 
An output from Intruder (which was used to perform the crash) along with the console output provided on a screenshot (by the way, I am not sure if its zip-encoder related - I keep getting that error message every time I upload a valid image)
![crash](https://cloud.githubusercontent.com/assets/1158719/26548894/916d3e9c-4476-11e7-855d-04c08923e8a5.png)

**Comment by sbehrens** [comment]
Hi @edwilded,

Are you running the server in production mode (fronted by Nginx and MySQL instead of SQLite?).

**Comment by ewilded** [comment]
Nope, that's a test instance ran from docker.

**Comment by sbehrens** [comment]
That sounds like some issue with pillow or pil, possibly missing some dependencies which are resulting in the exception.  

Can you try the following (within the virtualenv):

```
source sleepyenv/bin/activate
pip uninstall Pillow
sudo apt-get install libjpeg-dev zlib1g-dev
pip install -I Pillow
```

**Comment by sbehrens** [comment]
Once we clear up the error you are seeing we can dig a bit into the DoS and see if that's related to the embedded python server, sqlite, or the application code.  I'd be happy to try this out on my production deployment if you can provide a reference image upload (feel free to export your burp state (anonymized if needed)) and I could give it a try.

**Comment by ewilded** [comment]
Fair enough - dependencies installed; crash is gone :)

**Comment by sbehrens** [comment]
Great, I'll update the docs to include those deps.
