### ISSUE TITLE
Unable to create database while executing manage.py/unable to run testrun 

### ISSUE THREAD

**Issue by Blueberry-vignesh4303** [Netflix/sleepy-puppy#14]
Problem statement 

While executing manage.py error occurs

Error 

manage.py:19: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  from flask.ext.script import Manager
manage.py:20: ExtDeprecationWarning: Importing flask.ext.migrate is deprecated, use flask_migrate instead.
  from flask.ext.migrate import Migrate, MigrateCommand
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    from flask.ext.migrate import Migrate, MigrateCommand
  File "/home/Tools/sleepy-puppy/sleepypuppy/local/lib/python2.7/site-packages/flask/exthook.py", line 96, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/home/Tools/sleepy-puppy/sleepypuppy/local/lib/python2.7/site-packages/Flask_Migrate-2.1.1-py2.7.egg/flask_migrate/__init__.py", line 8, in <module>
    from alembic import __version__ as __alembic_version__
ImportError: No module named alembic

Operating system version 

Kali 2017.2

**Comment by sbehrens** [comment]
Can you create a new virtual env and checkout the latest master?  I went ahead and pinned to the correct version of `flask-migrate` which i believe will resolve the issue.

Thanks,
Scott

**Comment by Blueberry-vignesh4303** [comment]
Creating a new virtual env get it worked

Thanks for the patch
