### ISSUE TITLE
can't have the log

### ISSUE THREAD

**Issue by nx4dm1n** [Netflix/sleepy-puppy#16]
i 'm create a Assessment and enable "Access log"，copy an input the new payload in the html file，open the file in the chrome，and click the  "Capture" and "Access log"  ,the are nothing in it.

who can tell me  why ?  thanks !

**Comment by sbehrens** [comment]
Hi @nx4dm1n ,

You can't just open the html file, you'll need to host it on a webserver with a public IP address.  If the IP address is localhost, the browser wont issues a request.  Try the following with the file (assuming it's named index.html)

`python -m SimpleHTTPServer 8001`

Then visit your boxes (local IP not localhost) like the following:

`http://<ip>:8001`

Let me know if that works.

**Comment by nx4dm1n** [comment]
@sbehrens  thank you for your answer, this system is very good , and your method can resolve this question。
