### ISSUE TITLE
No module named flask_script.commands during installation

### ISSUE THREAD

**Issue by tfajks** [Netflix/sleepy-puppy#8]
during intalation I get an error:

python manage.py setup_sleepy_puppy

Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    from flask_script.commands import ShowUrls, Clean
ImportError: No module named flask_script.commands

**Comment by sbehrens** [comment]
Did you run into any issues running this command: 

`python setup.py install`

**Comment by scriptsrc** [comment]
Have you created and activated a virtual environment to install sleepypuppy into?

**Comment by tfajks** [comment]
Hi,
I've found reason, it's missing step with "deactivate" in wiki:
"
Install the required dependencies
python setup.py install
Create database, seed database, create default login with 'admin' user
**deactivate**
python manage.py setup_sleepy_puppy
"
regards,
Tomasz
