### ISSUE TITLE
session creation issue

### ISSUE THREAD

**Issue by pwneddesal** [Netflix/sleepy-puppy#9]
Hi, Whenever i authenticate myself using my credentials in sleepy-puppy web interface, My browser is alway redirected back to http://sleepy-puppy-ip/login/ and sometimes i get 403 forbidden error. i seem the session is not created.

**Comment by scriptsrc** [comment]
Interesting. I'm not sure why it would do that.

Have you tried creating a second user with the `manage.py` command?

https://github.com/Netflix/sleepy-puppy/blob/master/manage.py#L58

**Comment by pwneddesal** [comment]
problem solve thank you ! :dancer:

**Comment by pwneddesal** [comment]
The problem occurs again after a few hours and the proposed solution(creating new user) doesn't solve the problem anymore :( . I currently trying sleepy-puppy via c9.io

**Comment by scriptsrc** [comment]
Hey @deadstar1,

I'm wondering if c9.io is clearing the database after some period of time.  I'd connect to the DB and look through the user table.  Do that once when it's working, and once when it's broken.  My hunch is that the DB is getting reset on you.

**Comment by pwneddesal** [comment]
I don't think so. When  i create a user with a username, that already exists in the database, using `manage.py`. manage.py says `user already exists!` so c9.io does not clearing the database.

Sometimes the bug is triggered, sometimes not.

**Comment by sbehrens** [comment]
A proxy log of the requests would be helpful, if you can please use Burpsuite and record your proxy history during the login issues/403 forbidden. If you can send me that log it should help with troubleshooting.  Alternatively if you have information you need to redact, maybe take some screenshots of the Burp proxy log.

**Comment by pwneddesal** [comment]
**HTTP Request**
![httprequest](https://cloud.githubusercontent.com/assets/6646675/17777723/28ce8506-6594-11e6-8aff-19c14bda59a2.png)

**HTTP Response after an authentication**
![response](https://cloud.githubusercontent.com/assets/6646675/17777749/3fb20ea0-6594-11e6-90d6-44ede397621a.png)

**Console Log**

![consolelog](https://cloud.githubusercontent.com/assets/6646675/17777780/5616b3bc-6594-11e6-9249-e82ca8734a6e.png)

**Comment by sbehrens** [comment]
Do you have a TLS certificate configured and is the server listening on 443?

**Comment by pwneddesal** [comment]
I also installed sleepy-puppy in codeanywhere.com the same result was happened
![screenshot 2016-08-19 08 33 27](https://cloud.githubusercontent.com/assets/6646675/17795108/09212336-65e8-11e6-82c0-40d3fbec284d.png)

**Comment by sbehrens** [comment]
Looking back over your screenshots it looks like one of the POST requests results in a 400 HTTP error.  Something may be in the logs, could you perform the same authentication flow and send me over your nginx error log as well as any errors in sleepypuppy.log (in the root of the folder).

**Comment by sbehrens** [comment]
Also if you can provide the request/response screenshots for whatever call to /login is resulting in the 400 that would also be helpful!

**Comment by sbehrens** [comment]
Hi @deadstar1, just circling back on this.  Are you still having the same problem?

**Comment by pwneddesal** [comment]
look like there is no issue anymore. thanks
